// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk_i0cvq3qJ6MFij5kZfSsfdHB6UaiYnQ',
    appId: '1:1065162845238:web:8f27a3584f119dc1043c97',
    messagingSenderId: '1065162845238',
    projectId: 'talknep',
    authDomain: 'talknep.firebaseapp.com',
    storageBucket: 'talknep.firebasestorage.app',
    measurementId: 'G-KDQPYGL4KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVkUL2FRyu8ZMAmgDvbgFzRpxqVXBl3I',
    appId: '1:1065162845238:android:8859a532bfdfc160043c97',
    messagingSenderId: '1065162845238',
    projectId: 'talknep',
    storageBucket: 'talknep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qhSJ_YJl3Gz7jS5ZV0IHWSLm0mgtsP8',
    appId: '1:1065162845238:ios:b08bd87ee6fe6f78043c97',
    messagingSenderId: '1065162845238',
    projectId: 'talknep',
    storageBucket: 'talknep.firebasestorage.app',
    androidClientId: '1065162845238-6eqt677acs75tcgjosi75n875i2o4b2p.apps.googleusercontent.com',
    iosClientId: '1065162845238-g9k03pt5hige5173630ni2f8faejpg61.apps.googleusercontent.com',
    iosBundleId: 'com.talknep.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9qhSJ_YJl3Gz7jS5ZV0IHWSLm0mgtsP8',
    appId: '1:1065162845238:ios:b08bd87ee6fe6f78043c97',
    messagingSenderId: '1065162845238',
    projectId: 'talknep',
    storageBucket: 'talknep.firebasestorage.app',
    iosClientId: '1065162845238-g9k03pt5hige5173630ni2f8faejpg61.apps.googleusercontent.com',
    iosBundleId: 'com.talknep.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk_i0cvq3qJ6MFij5kZfSsfdHB6UaiYnQ',
    appId: '1:1065162845238:web:0bf2d90b7ec337dd043c97',
    messagingSenderId: '1065162845238',
    projectId: 'talknep',
    authDomain: 'talknep.firebaseapp.com',
    storageBucket: 'talknep.firebasestorage.app',
    measurementId: 'G-S3747QH94G',
  );
}